ServerEvents.tags('item', e =>{
    const materials = [
        'tconstruct:rose_gold_ingot',
        'tconstruct:rose_gold_nugget',
        'tconstruct:rose_gold_block',
        'tconstruct:cobalt_ingot',
        'tconstruct:cobalt_nugget',
        'tconstruct:cobalt_block',
        'tconstruct:raw_cobalt',
        'tconstruct:raw_cobalt_block',
        'tconstruct:cobalt_ore',
        'tconstruct:hepatizon_ingot',
        'tconstruct:hepatizon_nugget',
        'tconstruct:hepatizon_block',
        'tconstruct:manyullyn_ingot',
        'tconstruct:manyullyn_nugget',
        'tconstruct:manyullyn_block',
        'tconstruct:amethyst_bronze_ingot',
        'tconstruct:amethyst_bronze_nugget',
        'tconstruct:amethyst_bronze_block',
        'tconstruct:slimesteel_ingot',
        'tconstruct:slimesteel_nugget',
        'tconstruct:slimesteel_block',
        'create:brass_ingot',
        'create:brass_nugget',
        'create:brass_block',
        'create:zinc_ingot',
        'create:zinc_nugget',
        'create:zinc_block',
        'create:brass_sheet',
        'create:copper_sheet',
        'create:copper_sheet',
        'create:golden_sheet',
        /create:.*_sheet/,
        / exdeorum:.* _ore_chunk /,
        /thermal:.*_plate/,
        / thermal:.* _coin /,

        /thermal:bronze_.*/,
        / thermal: silver_.*/,
        / thermal: tin_.*/,
        / thermal: lead_.*/,
        / thermal: nickel_.*/,
        / thermal: electrum_.*/,
        / thermal: invar_.*/,
        / thermalendergy: melodium_.*/,
        / thermalendergy: stellarium_.*/,
        / thermal_extra: dragonsteel_.*/,
        / thermal_extra: shellite_.*/,
        / thermal_extra: twinite_.*/,
        / thermalendergy: prismalium_.*/,
        / thermal: enerium_.*/,
        / thermal: signalum_.*/,
        / thermal: enderium_.*/,
        / thermal: lumium_.*/,
        / thermal: constantan_.*/,
        / thermal:.* _gear /,
        /thermal:.*_dust/,
        / thermal:.* _slag /,
        /thermal:.*_nugget/,
        / thermal:.* _sulfur /,
        /thermal:.*_rockwool/,
        / thermal_extra: soul_infused_.*/,
        / thermal_extra: signalum_.*/,
        / thermal_extra: enderium_.*/,
        / thermal_extra: lumium_.*/,
        / thermal_extra: abyssal_.*/,
        / thermal_extra:.* _rod /,
    ]

    materials.forEach(remove => {
        e.removeAllTagsFrom(`${remove}`)
    })
})