JEIEvents.hideItems( e => {
    const hideItems = [
        'tconstruct:rose_gold_ingot',
        'tconstruct:rose_gold_nugget',
        'tconstruct:rose_gold_block',
        'tconstruct:cobalt_ingot',
        'tconstruct:cobalt_nugget',
        'tconstruct:cobalt_block',
        'tconstruct:raw_cobalt',
        'tconstruct:raw_cobalt_block',
        'tconstruct:cobalt_ore',
        'tconstruct:hepatizon_ingot',
        'tconstruct:hepatizon_nugget',
        'tconstruct:hepatizon_block',
        'tconstruct:manyullyn_ingot',
        'tconstruct:manyullyn_nugget',
        'tconstruct:manyullyn_block',
        'create:brass_ingot',
        'create:brass_nugget',
        'create:brass_block',
        'create:zinc_ingot',
        'create:zinc_nugget',
        'create:zinc_block',
        'exdeorum:sculk_core',
        'exdeorum:crushed_deepslate',
        'exdeorum:crushed_end_stone',
        'exdeorum:crushed_netherrack',
    ]
    hideItems.forEach(hide =>{
        e.hide(`${hide}`)
    })
    const mod = [
        'create:',
        'thermal:',
        //'create_new_age:',
        'exdeorum:',
        //'exmachinis:'
    ]
    const hide = [
        'brass_ingot',
        'zinc_ingot',
        'brass_block',
        'zinc_block',
        'brass_nugget',
        'zinc_nugget',
        'brass_sheet',
        'copper_sheet',
        'golden_sheet',
        'iron_sheet',
        'sturdy_sheet',
        'thorium',
        'nuclear_fuel',
        'reactor_glass',
        'reactor_casing',
        'basic_motor_extension',
        'advanced_motor_extension',
        'heat_pump',
        'copper_circuit',
        'blank_circuit',
        'reactor_heat_vent',
        'reactor_fuel_acceptor',
        'reactor_rod',
        'heater',
        'stirling_engine',
        'basic_solar_heating_plate',
        'advanced_solar_heating_plate',
        'heat_pipe',
        'solid_corium',
        'corium',
        'incomplete_fuel',
        'incomplete_casing',
        'radioactive_thorium',
        'thorium_ore',
        'mechanical_hammer',
        'mechanical_sieve',
        'item_buffer',
        'flux_compactor',
        'flux_hammer',
        'saw_blade',
        'drill_head',
        'fluid_duct_windowed',
        'fluid_duct',
        'energy_duct',
        'niter_block',
        'sulfur_block',
        'cinnabar_block',
        'apatite_block',
        'bitumen',
        'cinnabar_dust',
        'niter',
        'cinnabar',
        'sawdust',
        'coal_coke',
        'apatite',
        'apatite_dust',
        'rich_slag',
        'slag',
        'tar',
        'satchel',
        'lock',
        'redprint',
        'wrench',
        'detonator',
        'florb',
        'slot_seal',
        'area_radius_augment',
        'machine_catalyst_augment',
        'machine_null_augment',
        'machine_cycle_augment',
        'filter_attachment',
        'turbo_servo_attachment',
        'energy_limiter_attachment',
        'servo_attachment',
        'redprint',
        'sapphire',
        'ruby',
        'slag_bricks',
        'device_soil_infuser',
        'item_filter_augment',
        'fluid_tank_creative_augment',
        'xp_storage_augment',
        'side_config_augment',
        'rs_control_augment',
        'light_oil_bucket',
        'heavy_oil_bucket',
        'crude_oil_bucket',
        'creosote_bucket',
        'syrup_bucket',
        'sap_bucket',
        'ender_bucket',
        'glowstone_bucket',
        'redstone_bucket',
        'dragonsteel_bucket',
        'twinite_bucket',
        'shellite_bucket',
        'soul_infused_bucket',
        'refined_fuel_bucket'
    ]
    const rex = [
        /create:crushed_.*/,
        ///create:crushed_.*/,
        /exdeorum:.*compressed_sieve/,
        /exdeorum:.*_ore_chunk/,
        ///exdeorum:porcelain_.*_bucket/,

        /thermal:bronze.*/,
        /thermal:bronze_.*/,
        /thermal:silver_.*/,
        /thermal:tin_.*/,
        /thermal:lead_.*/,
        /thermal:nickel_.*/,
        /create:.*_sheet/,
        /exdeorum:.*_ore_chunk/,
        /thermal:.*_plate/,
        /thermal:.*_coin/,
        /thermal:.*_ingot/,
        /thermal:.*_dust/,
        /thermal:.*_block/,
        /thermal:raw_.*/,

        /thermalendergy:melodium_.*/,
        /thermalendergy:stellarium_.*/,
        /thermal_extra:dragonsteel_.*/,
        /thermal_extra:shellite_.*/,
        /thermal_extra:twinite_.*/,
        /thermalendergy:prismalium_.*/,
        /thermal:machine_.*/,
        /thermal:.*_ore/,
        /thermal:.*_gear/,
        /thermal:.*_dust/,
        /thermal:.*_slag/,
        /thermal:.*_nugget/,
        /thermal:.*_slag/,
        /thermal:.*_nugget/,
        /thermal:.*_sulfur/,
        /thermal:.*_rockwool/,
        /thermal_extra:soul_infused_.*/,
        /thermal:hazmat_.*/,
        /thermal:diving_.*/,
        /thermal:beekeeper_.*/,
        /thermal:.*_grenade/,
        /thermal:.*_tnt/,
        /thermal:press_.*/,
        /thermal:chiller_.*/,
        /thermal_extra:area_radius_augment_.*/,
        /thermal_extra:potion_amplifier_augment_.*/,
        /thermal_extra:machine_speed_augment_.*/,
        /thermal_extra:machine_output_augment_.*/,
        /thermal_extra:machine_catalyst_augment_.*/,
        /gtceu:.*_indicator/,
        /ae2:facade/,
        /exdeorum:compressed_.*_hammer/,
        /exdeorum:compressed_.*/,


    ]
    rex.forEach((rex) => {
        event.hide(`${rex}`)
    })
    mod.forEach((mod) => {
        hide.forEach((hide) => {
            event.hide(`${mod}${hide}`)
        })
    })
})
JEIEvents.addItems(event => {
    event.add(Item.of('thermal:signalum_glass'))
    event.add('thermal:lumium_glass')
    event.add('thermal:enderium_glass')
})
JEIEvents.hideFluids(event => {
    event.hide('thermal:light_oil')
    event.hide('thermal:heavy_oil')
    event.hide('thermal:crude_oil')
    event.hide('thermal:creosote')
    event.hide('thermal:syrup')
    event.hide('thermal:sap')
    event.hide('thermal:ender')
    event.hide('thermal:redstone')
    event.hide('thermal_extra:dragonsteel')
    event.hide('thermal_extra:twinite')
    event.hide('thermal_extra:shellite')
    event.hide('thermal_extra:soul_infused')
    event.hide('thermal:refined_fuel')
})

JEIEvents.removeCategories(event => {
    event.remove('thermal:furnace')
})